flutter/news_toolkit

docs/docs/project_configuration/app_deployment.md

Fix typo as pipeuline -> pipeline

---

docs/docs/project_configuration/api_deployment.md

docs: add cloud run deployment steps

---

flutter_news_example/lib/login/widgets/login_with_email_form.dart
flutter_news_example/lib/magic_link_prompt/view/magic_link_prompt_view.dart
flutter_news_example/lib/onboarding/view/onboarding_view.dart
flutter_news_example/lib/onboarding/widgets/onboarding_view_item.dart
flutter_news_example/lib/user_profile/view/user_profile_page.dart
flutter_news_example/test/onboarding/view/onboarding_view_test.dart
flutter_news_example/test/user_profile/view/user_profile_page_test.dart

- refactor: remove ScrollableColumn private usages (closes https://github.com/flutter/flutter/issues/119137)

refactor: remove ScrollableColumn private usages

---

flutter_news_template/CHANGELOG.md
flutter_news_template/brick.yaml

- fix: add missing permissions for ads on android 13
- fix: interstitial ads behavioral improvements
- refactor: remove ScrollableColumn private usages
- refactor: upgrade to Dart 2.19 and Flutter 3.7

chore: v1.0.1

---

docs/docs/project_configuration/upgrading.md

- docs(upgrading): add upgrading your project section

docs(upgrading): add upgrading your project section

---

docs/package-lock.json

- chore(deps): upgrade docs site dependencies

chore(deps): upgrade docs site dependencies

---

docs/docs/overview.md

docs: update dart frog description

---

flutter_news_template/CHANGELOG.md
flutter_news_template/brick.yaml

- fix: issues with first login
- docs: fix android emulator address
- docs: update Dart Frog description

chore: v1.0.2

---

flutter_news_example/lib/l10n/arb/app_en.arb

chore: remove unused translations

---

docs/docs/overview.md

docs: add contribution documentation and issue guidelines

---

flutter_news_example/api/pubspec.lock
flutter_news_example/api/pubspec.yaml

Reverts flutter/news_toolkit#845

Revert "chore(deps): Bump dart_frog from 0.3.3 to 0.3.5 in /flutter_news_example/api"

---

flutter_news_template/CHANGELOG.md
flutter_news_template/brick.yaml

- refactor: lazy load PostGrid

chore: v1.0.3

---

flutter_news_template/CHANGELOG.md
flutter_news_template/brick.yaml

- chore: updating template generation bot

chore: v1.0.4

---

.github/CODEOWNERS

chore: Update CODEOWNERS to add Mark Fairless

---

docs/docs/flutter_development/cache_application_state.md
docs/docs/flutter_development/privacy_policy.md

Last version of the documentation is not showing latest changes (addition of the Hydrated Bloc documentation). Swapped last pages positions on the sidebar to force a re-deploy to Github Pages.

Fix: Swap doc pages

---

flutter_news_example/api/packages/news_blocks/pubspec.yaml
flutter_news_example/api/pubspec.yaml
flutter_news_example/packages/ads_consent_client/pubspec.yaml
flutter_news_example/packages/analytics_repository/pubspec.yaml
flutter_news_example/packages/app_ui/pubspec.yaml
flutter_news_example/packages/article_repository/pubspec.yaml
flutter_news_example/packages/authentication_client/firebase_authentication_client/pubspec.yaml
flutter_news_example/packages/authentication_client/token_storage/pubspec.yaml
flutter_news_example/packages/deep_link_client/pubspec.yaml
flutter_news_example/packages/email_launcher/pubspec.yaml
flutter_news_example/packages/in_app_purchase_repository/pubspec.yaml
flutter_news_example/packages/news_blocks_ui/pubspec.yaml
flutter_news_example/packages/news_repository/pubspec.yaml
flutter_news_example/packages/notifications_client/firebase_notifications_client/pubspec.yaml
flutter_news_example/packages/notifications_client/one_signal_notifications_client/pubspec.yaml
flutter_news_example/packages/notifications_repository/pubspec.yaml
flutter_news_example/packages/permission_client/pubspec.yaml
flutter_news_example/packages/share_launcher/pubspec.yaml
flutter_news_example/packages/storage/persistent_storage/pubspec.yaml
flutter_news_example/packages/storage/secure_storage/pubspec.yaml
flutter_news_example/packages/user_repository/pubspec.yaml
flutter_news_example/pubspec.yaml

- Bump `mocktail`, `mockingjay` and `mocktail_image_network` to their latest version.

chore: bump mocktail dependency

---

flutter_news_example/lib/l10n/arb/app_en.arb

Change the Localization type parameter from `text` to `String`.
Some updates are due to spacing or formatting.

refactor: change the localization type parameter from `text` to `String`

---

flutter_news_template/CHANGELOG.md
flutter_news_template/__brick__/{{project_name.snakeCase()}}/codemagic.yaml
flutter_news_template/brick.yaml
flutter_news_template/hooks/pre_gen.dart

- When using the mason brick to create a new project it was being created with an old flutter version (3.3.10). Updated flutter version on `pre_gen.dart` script and `codemagic.yaml` file to match the last version that the toolkit was updated to so that the project gets generated with this version.
- Upgraded `brick.yaml` version and added new changes to `changelog.md` file.

Chore: v1.0.6

---

flutter_news_template/CHANGELOG.md
flutter_news_template/brick.yaml

- Fixed issue when running `build_runner` to generate the generated code for the API models, since it was causing some of the API tests to fail.
- Changed return type of `NewsBlockConverter()` from List<Map<String, dynamic>> `List<dynamic>`. This was causing tests to fail.
- Added `explicitToJson` statements to some models that had complex attributes inside, like another model. This was also causing tests to fail.
- Upgraded `brick.yaml` version and added new changes to `changelog.md` file.

Chore: v1.0.7

---

docs/docs/project_configuration/social_authentication.md

Fix typo
Just a minor typo fix: followint -> following

Fix Typo in social_authentication.md

---

flutter_news_template/CHANGELOG.md
flutter_news_template/brick.yaml

- Chore: updated dependencies.
- Fix: updated documentation typo in `social_authentication.md`
- Fix issue where project was not running when generating it with only `production` flavor. Solution was to remove  GoogleService-Info.plist copy in iOS project
- Revert change that is causing mason template generation issue

Chore: v1.0.8

---

docs/docs/project_configuration/social_authentication.md

Add paragraphs on `social_authentication.md` to specify all the environment variables and user defined settings (Xcode) that the users have to fill once finished the configuration of a specific social authentication method. Updated Email sign in, Facebook and Twitter methods.
Fixes https://github.com/flutter/flutter/issues/140463

docs: update social_authentication.md

---

flutter_news_template/CHANGELOG.md
flutter_news_template/brick.yaml

- chore: update dependencies
- fix: Remove Podfile.lock from iOS project [[#141462]](https://github.com/flutter/flutter/issues/141462)

Chore: v1.0.9

---

docs/docs/overview.md

docs: update docs to match new dart sdk version required

---

flutter_news_template/CHANGELOG.md
flutter_news_template/brick.yaml

chore: v1.0.10

---

docs/docs/overview.md

Part of https://github.com/flutter/flutter/issues/145009

Update old wiki links

---

.github/workflows/news_blocks_ui.yaml
flutter_news_example/packages/news_blocks_ui/test/helpers/tolerant_comparator.dart
flutter_news_example/packages/news_blocks_ui/test/src/article_introduction_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/divider_horizontal_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/post_large/post_large_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/post_medium/post_medium_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/post_small_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/section_header_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/spacer_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/text_caption_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/text_headline_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/text_lead_paragraph_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/text_paragraph_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/trending_story_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/video_introduction_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/widgets/banner_ad_content_test.dart
flutter_news_example/packages/news_blocks_ui/test/src/widgets/post_footer_test.dart

fix(ci): golden test comparator implementation

---

flutter_news_template/CHANGELOG.md
flutter_news_template/brick.yaml

chore: v1.0.11

---

flutter_news_template/CHANGELOG.md
flutter_news_template/brick.yaml

chore: v1.0.12

---

flutter_news_example/android/app/build.gradle
flutter_news_example/android/build.gradle
flutter_news_example/android/settings.gradle

refactor: migrate gradle plugins to declarative approach

---

flutter_news_template/CHANGELOG.md
flutter_news_template/brick.yaml

chore: v1.0.13

---

tool/generator/static/build.gradle

- Most of changes are related to [1301](https://github.com/flutter/news_toolkit/pull/1301/files)

fix: add missing build.gradle changes

---

.github/workflows/main.yaml
flutter_news_template/CHANGELOG.md
flutter_news_template/brick.yaml
flutter_news_template/hooks/pre_gen.dart
flutter_news_template/hooks/pubspec.yaml

chore: v1.0.14

---

.github/workflows/dependabot.yaml

Dependabot needs to be added to the main branch, based on the [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch). Removing it from templates branch.

fix: remove dependabot from templates

---

.github/dependabot.yaml

As part of the https://github.com/flutter/flutter/issues/159641 regarding Mason being outdated, adding DependaBot to take care of keeping everything up to date is the go-to solution.

feat: add dependabot for templates

---

flutter_news_template/brick.yaml
flutter_news_template/hooks/pubspec.yaml

In order to allow Dependabot to take care of future Mason versions, Flutter version also needs to be updated.

feat: update flutter and mason version

---

flutter_news_template/CHANGELOG.md
flutter_news_template/brick.yaml

- chore: upgrade mason to 0.1.0
- chore: upgrade dependencies

chore: v1.0.15
